### ISSUE TITLE
FabricGateway::Gatewayの早すぎるClose

### ISSUE THREAD

**Issue by siburu** [datachainlab/relayer#6]
https://github.com/datachainlab/relayer/blob/563073a9c2a62345123e202cc9817810f652839d/chains/fabric/gateway.go#L74

このClose関数ですが、今のところ中身が空なので問題になってませんが、意味的には以下のとおりなのでここでCloseしてしまうのは不味いのではないかと。
```
// Close the gateway connection and all associated resources, including removing listeners attached to networks and
// contracts created by the gateway.
```

**Comment by bluele** [comment]
Thanks, this is fixed at 7e5f897c01308661112dbbf5319952f5afc7b3a6 .
However, this is just a workaround. We will probably need to provide a destructor to correctly destroy each resource in Chain.
